package opcode

const (
	SendLoginResponse         int16 = 1
	SendLoginWorldMeta        int16 = 3
	SendLoginPinOperation     int16 = 6
	SendLoginWorldList        int16 = 10
	SendLoginCharacterData    int16 = 11
	SendLoginCharacterMigrate int16 = 12

	SendLoginNameCheckResult  int16 = 13
	SendLoginNewCharacterGood int16 = 14
	SendLoginDeleteCharacter  int16 = 15

	SendLoginRelogResponse             int16 = 22
	SendChannelChange                  int16 = 0x0F
	SendLoginRestarter                 int16 = 0x15
	SendChannelInventoryOperation      int16 = 0x19
	SendChannelInventoryGrow           int16 = 0x1A
	SendChannelStatChange              int16 = 0x1B
	SendChannelTempStatChange          int16 = 0x1C
	SendChannelRemoveTempStat          int16 = 0x1D
	SendChannelSkillRecordUpdate       int16 = 0x1E
	SendChannelSkillUseResult          int16 = 0x1F
	SendChannelFameOperation           int16 = 0x20
	SendChannelMessage                 int16 = 0x21
	SendChannelInfoMessage             int16 = 0x21
	SendChannelMapTransferResult       int16 = 0x23
	SendChannelLieDetectorTest         int16 = 0x24
	SendChannelQuestComplete           int16 = 0x29
	SendChannelAvatarInfoWindow        int16 = 0x31
	SendChannelPartyInfo               int16 = 0x32
	SendChannelBuddyInfo               int16 = 0x33
	SendChannelGuildInfo               int16 = 0x35
	SendChannelTownPortal              int16 = 0x36
	SendChannelBroadcastMessage        int16 = 0x37
	SendChannelWarpToMap               int16 = 0x49
	SendChannelSetCashShop             int16 = 0x4A
	SendChannelPortalClosed            int16 = 0x4D
	SendChannelChangeServer            int16 = 0x4E
	SendChannelBubblessChat            int16 = 0x50
	SendChannelWhisper                 int16 = 0x51
	SendChannelMapEffect               int16 = 0x54
	SendChannelBlowWeather             int16 = 0x55
	SendChannelPlayJukebox             int16 = 0x56
	SendChannelEmployee                int16 = 0xBC
	SendChannelQuizQAndA               int16 = 0x58
	SendChannelTimer                   int16 = 0x59
	SendChannelMovingObj               int16 = 0x61
	SendChannelBoat                    int16 = 0x5D
	SendChannelPlayerPartyHP           int16 = 0x8C
	SendChannelCharacterEnterField     int16 = 0x64
	SendChannelCharacterLeaveField     int16 = 0x65
	SendChannelAllChatMsg              int16 = 0x67
	SendChannelRoomBox                 int16 = 0x69
	SendChannelUseScroll               int16 = 0x6B
	SendChannelPetSpawn                int16 = 0x6C
	SendChannelPetMove                 int16 = 0x6D
	SendChannelPetAction               int16 = 0x6E
	SendChannelPetNameChange           int16 = 0x6F
	SendChannelPetInteraction          int16 = 0x70
	SendChannelSpecialMapObjectSpawn   int16 = 0x75
	SendChannelSpecialMapObjectRemove  int16 = 0x76
	SendChannelSummonMove              int16 = 0x77
	SendChannelSummonAttack            int16 = 0x78
	SendChannelSummonDamage            int16 = 0x79
	SendChannelPlayerMovement          int16 = 0x7E
	SendChannelPlayerUseMeleeSkill     int16 = 0x7F
	SendChannelPlayerUseRangedSkill    int16 = 0x80
	SendChannelPlayerUseMagicSkill     int16 = 0x81
	SendChannelPlayerPrepareSkill      int16 = 0x82
	SendChannelPlayerStopSkill         int16 = 0x83
	SendChannelPlayerTakeDmg           int16 = 0x84
	SendChannelPlayerAnimation         int16 = 0x85
	SendChannelPlayerActiveEffect      int16 = 0x86
	SendChannelPlayerSit               int16 = 0x87
	SendChannelPlayerChangeAvatar      int16 = 0x88
	SendChannelPlayerEmoticon          int16 = 0x89
	SendChannelPlayerGiveForeignBuff   int16 = 0x8A
	SendChannelPlayerResetForeignBuff  int16 = 0x8B
	SendChannelPlayerSitResult         int16 = 0x91
	SendChannelPlayerEffect            int16 = 0x93
	SendChannelQuestActionResult       int16 = 0x97
	SendChannelSkillCooldown           int16 = 0x9A
	SendChannelShowMob                 int16 = 0x9E
	SendChannelRemoveMob               int16 = 0x9F
	SendChannelControlMob              int16 = 0xA0
	SendChannelMoveMob                 int16 = 0xA2
	SendChannelControlMobAck           int16 = 0xA3
	SendChannelMobStatSet              int16 = 0xA5
	SendChannelMobStatReset            int16 = 0xA6
	SendChannelMobAffected             int16 = 0xA8
	SendChannelMobDamage               int16 = 0xA9
	SendChannelMobSpecialEffectBySkill int16 = 0xAA
	SendChannelNpcShow                 int16 = 0xB1
	SendChannelNpcRemove               int16 = 0xB2
	SendChannelNpcControl              int16 = 0xB3
	SendChannelNpcMovement             int16 = 0xB5
	SendChannelDropEnterMap            int16 = 0xC1
	SendChannelDropExitMap             int16 = 0xC2
	SendChannelAffectedAreaCreate      int16 = 0xCA
	SendChannelAffectedAreaRemove      int16 = 0xCB
	SendChannelSpawnDoor               int16 = 0xCE
	SendChannelRemoveDoor              int16 = 0xCF
	SendChannelReactorChangeState      int16 = 0xD2
	SendChannelReactorEnterField       int16 = 0xD4
	SendChannelReactorLeaveField       int16 = 0xD5
	SendChannelNpcDialogueBox          int16 = 0xE2
	SendChannelNpcShop                 int16 = 0xC9 // unverified in v48 named IDB; kept from previous table for now
	SendChannelNpcShopResult           int16 = 0xCA // unverified in v48 named IDB; kept from previous table for now
	SendChannelNpcStorage              int16 = 0xEA // verified via CStoreBankDlg::OnPacket
	SendChannelNpcStorageResult        int16 = 0xEB // verified via CStoreBankDlg::OnPacket
	SendChannelMessenger               int16 = 0xEE
	SendChannelRoom                    int16 = 0xEF
	SendChannelCSRecharge              int16 = 0xE8
	SendChannelCSUpdateAmounts         int16 = 0xE9 // unverified in v48 named IDB; retained pending cash shop audit
	SendChannelCSAction                int16 = 0xEA // unverified in v48 named IDB; retained pending cash shop audit
)
